/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include"main.h"

void delay(void)
{
	for(uint32_t i=0;i<300000;i++);

}

int main(void)
{

	RCC_AHBIENR_t *AHB1ENR = ADDR_REG_AHB1ENR;
	GPIOx_MODER_t   *GPIOA_MODER = ADDR_REG_GPIOA_MODE;
	GPIOx_ODR_t  *GPIOA_ODR=ADDR_GPIOA_ODR;

	GPIOx_MODER_t   *GPIOC_MODER = ADDR_REG_GPIOC_MODE;
	GPIOx_ODR_t  *GPIOC_ODR=ADDR_GPIOC_ODR;


	AHB1ENR->gpioc_en=1;// ENABLE CLK FOR GPIOC
	AHB1ENR->gpioa_en=1;

	GPIOA_MODER->moder_5=1; // OUTPUT MODE 01

	GPIOC_MODER->moder_0=1; // OUTPUT MODE 01
	GPIOC_MODER->moder_1=1; // OUTPUT MODE 01
	GPIOC_MODER->moder_2=1; // OUTPUT MODE 01
	GPIOC_MODER->moder_3=1; // OUTPUT MODE 01
	GPIOC_MODER->moder_4=1; // OUTPUT MODE 01
	GPIOC_MODER->moder_5=1; // OUTPUT MODE 01
	GPIOC_MODER->moder_6=1; // OUTPUT MODE 01
	GPIOC_MODER->moder_7=1; // OUTPUT MODE 01
	GPIOC_MODER->moder_8=1; // OUTPUT MODE 01

	while(1)
	{
	GPIOC_ODR->ODR_0_7=0XAA;
	GPIOA_ODR->ODR_0_7=0XAA;

	/*GPIOC_ODR->ODR_1=1;
	GPIOC_ODR->ODR_2=1;
	GPIOC_ODR->ODR_3=1;
	GPIOC_ODR->ODR_4=1;
	GPIOC_ODR->ODR_5=1;
	GPIOC_ODR->ODR_6=1;
	GPIOC_ODR->ODR_7=1;
	GPIOC_ODR->ODR_8=1; */

	delay();
	GPIOC_ODR->ODR_0_7=0X00;
	GPIOA_ODR->ODR_0_7=0X00;


	//GPIOC_ODR->ODR_0=0;
	/*GPIOC_ODR->ODR_1=0;
	GPIOC_ODR->ODR_2=0;
	GPIOC_ODR->ODR_3=0;
	GPIOC_ODR->ODR_4=0;
	GPIOC_ODR->ODR_5=0;
	GPIOC_ODR->ODR_6=0;
	GPIOC_ODR->ODR_7=0;
	GPIOC_ODR->ODR_8=0;
*/
	delay();

	}

	for(;;);
}
