/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdio.h>
#include <stdint.h>

void delay(void){
	for(volatile uint32_t i=0; i<300000; i++);
}

int main(void)
{
	uint32_t *portcAHB1ENR = (uint32_t *) 0X40023830;
	uint32_t *portcMODER = (uint32_t *) 0X40020800;
	uint32_t *portcODR = (uint32_t *) 0X40020814;
	uint32_t *portcIDR = (uint32_t *)0X40020810;
	uint32_t *portcPUPDR = (uint32_t *) 0X4002080C;

	//Enable peripheral CLK for GPIOC
	*portcAHB1ENR |= (1<<2);
	//*portcAHB1ENR |= 0X04;

	//Enable PC0 - PC3 to OUTPUT
	//       PC4 - PC7 to INPUT
	*portcMODER &= 0XFFFF0000;
	*portcMODER |= 0X00000055;

	*portcPUPDR &= 0XFFFF0000;
	*portcPUPDR |= 0X55000000;

	while(1){
		*portcODR |= 0X0F;
		*portcODR &= ~(1<<0);

		//MAKE ROW (1) LOW
		if(!(*portcIDR & (1<<4))){
			delay();
			printf("1 is pressed. \n");
		}
		if(!(*portcIDR & (1<<5))){
			delay();
			printf("2 is pressed. \n");
		}
		if(!(*portcIDR & (1<<6))){
			delay();
			printf("3 is pressed. \n");
		}
		if(!(*portcIDR & (1<<7))){
			delay();
			printf("4 is pressed. \n");
		}

		//MAKE ROW (2) LOW
		if(!(*portcIDR & (1<<4))){
			delay();
			printf("5 is pressed. \n");
		}
		if(!(*portcIDR & (1<<5))){
			delay();
			printf("6 is pressed. \n");
		}
		if(!(*portcIDR & (1<<6))){
			delay();
			printf("7 is pressed. \n");
		}
		if(!(*portcIDR & (1<<7))){
			delay();
			printf("8 is pressed. \n");
		}

//MAKE ROW (3) LOW
		if(!(*portcIDR & (1<<4))){
			delay();
			printf("9 is pressed. \n");
		}
		if(!(*portcIDR & (1<<5))){
			delay();
			printf("10 is pressed. \n");
		}
		if(!(*portcIDR & (1<<6))){
			delay();
			printf("11 is pressed. \n");
		}
		if(!(*portcIDR & (1<<7))){
			delay();
			printf("12 is pressed. \n");
		}

//MAKE ROW (4) LOW
		if(!(*portcIDR & (1<<4))){
			delay();
			printf("13 is pressed. \n");
		}
		if(!(*portcIDR & (1<<5))){
			delay();
			printf("14 is pressed. \n");
		}
		if(!(*portcIDR & (1<<6))){
	    	delay();
			printf("15 is pressed \n.");
		}
		if(!(*portcIDR & (1<<7))){
		    delay();
			printf("16 is pressed. \n");
		}
	} //End loop



	for(;;);
}
