/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>

int main(void)
{
    uint32_t *AHB1ENR = (uint32_t*) 0x40023830;
    //base address 0X40023800 + offset address 0X30
    uint32_t *MODER = (uint32_t*) 0x40020000;
    // 0x40020000 + 0X00
    uint32_t *ODR = (uint32_t*) 0x40020014;
    // 0x40020000 + 0X14


    *AHB1ENR |= 0X01; //Enable GPIOA
	*MODER &= 0XFFFFF3FF; // Clear pin 5
	*MODER |= 0X00000400; //Set pin 5 (0400 = b'0100)

	*ODR |= 0X20;  //set ODR register

	for(;;);
}






